apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungeecord-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bungeecord
  template:
    metadata:
      labels:
        app: bungeecord
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bungeecord
        image: itzg/bungeecord
        command: ["/bin/bash", "/bungeecord-config/start.sh"]
        ports:
        - containerPort: 25577
        volumeMounts:
        - name: bungeecord-config
          mountPath: /bungeecord-config
      volumes:
      - name: bungeecord-config
        configMap:
          name: bungeecord-config
---
apiVersion: v1
kind: Service
metadata:
  name: bungeecord-service
  labels:
    app: bungeecord
spec:
  selector:
    app: bungeecord
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 25565
     targetPort: 25577
  sessionAffinity: ClientIP
