apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-spigot-deployment
spec:
  selector:
    matchLabels:
      app: lobby-spigot
  serviceName: "lobby-spigot"
  template:
    metadata:
      labels:
        app: lobby-spigot
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: lobby-spigot
        image: itzg/minecraft-server
        command: ["/bin/bash", "/spigot-config/start.sh"]
        env:
          - name: EULA
            value: "TRUE"
          - name: TYPE
            value: "SPIGOT"
          - name: VERSION
            value: 1.13.2
          #- name: BUILD_FROM_SOURCE
          #  value: "TRUE"
          - name: SPIGOT_DOWNLOAD_URL
            value: "https://storage.googleapis.com/saizo-spigot-plugins/spigot_server.jar"
          - name: ONLINE_MODE
            value: "FALSE"
          - name: MAX_TICK_TIME
            value: "-1"
          - name: MODE
            value: "creative"
          - name: FORCE_GAMEMODE
            value: "TRUE"
          - name: PVP
            value: "FALSE"
          - name: LEVEL_TYPE
            value: "FLAT"
        livenessProbe:
          exec:
            command:
              - mcstatus
              - localhost
              - ping
          initialDelaySeconds: 800
          periodSeconds: 10
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: data
          mountPath: /data
        - name: spigot-config
          mountPath: /spigot-config
      volumes:
      - name: spigot-config
        configMap:
          name: spigot-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: "minecraft-data"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-spigot-service
  labels:
    app: lobby-spigot
spec:
  selector:
    app: lobby-spigot
  type: ClusterIP
  #type: NodePort
  ports:
   - protocol: TCP
     port: 25566
     targetPort: 25565
